fetch_papers:
  description: >
    Fetch research papers using smart fetching from ArXiv and HuggingFace.
    Extract title, abstract, authors, publication date, paper URL, and ArXiv ID.
    Ensure proper categorization and deduplication of papers.
  expected_output: >
    A list of research papers with complete metadata including title, abstract, 
    authors, publication date, ArXiv ID, and direct links to papers.

summarize_papers:
  description: >
    Create structured summaries for each research paper including key contributions,
    methodology, significance, and technical overview. Categorize each paper.
    The output must include all fields: key_contributions, methodology, significance,
    technical_summary, practical_applications, limitations, primary_category,
    and difficulty_level.
  expected_output: >
    A list of papers with complete summaries, where each paper contains:
    - key_contributions (list)
    - methodology (string)
    - significance (string)
    - technical_summary (string)
    - practical_applications (string)
    - limitations (string)
    - primary_category (string)
    - difficulty_level (string)

store_papers:
  description: >
    Store the processed research papers and their summaries in Supabase database.
    Ensure all required fields are present: title, abstract, authors, primary_category,
    and technical_summary. Also store optional fields if available.
  expected_output: >
    Confirmation of successful database storage with number of papers stored. 